drop table Users CASCADE CONSTRAINTS;
drop table Dataset CASCADE CONSTRAINTS;
drop table DatasetBelonging CASCADE CONSTRAINTS;
drop table Image CASCADE CONSTRAINTS;
drop table ImageArea CASCADE CONSTRAINTS;
drop table Label CASCADE CONSTRAINTS;
drop table Classification CASCADE CONSTRAINTS;

create table Users (
    user_id number generated by default as identity primary key,
    username varchar2(15) not null unique,
    role varchar2(1) not null,
    password_hash varchar2(20)
);

create table Dataset (
    dataset_id number generated by default as identity primary key,
    name varchar2(40) not null unique,
    description varchar2(300),
    date_created date,
    created_by number not null references Users
);

create table Image (
    image_id number generated by default as identity primary key,
    content varchar2(150) not null
);

create table DatasetBelonging (
    image_id number not null references Image,
    dataset_id number not null references Dataset
);

create table ImageArea (
    area_id number generated by default as identity primary key,
    x number not null,
    y number not null,
    width number not null,
    height number not null,
    image_id number not null references Image,
    contradictory_labels number(1)
);

create table Label (
    label_id number generated by default as identity primary key,
    name varchar2(20) not null unique,
    parent_id number references Label,
    depth number
);

create table Classification (
    class_id number generated by default as identity primary key,
    area_id number not null references ImageArea,
    created_by number not null references Users,
    label_id number not null references Label
);

commit;